const $=s=>document.querySelector(s), app=$('#app'), cfg=window.POLL_CONFIG;
const configured=cfg && !cfg.supabaseUrl.includes('PASTE_');
const db=configured?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const id=()=>location.hash.replace(/^#\/?/,'').trim();
$('#manageLink').onclick=()=>{location.hash='manage'}; window.addEventListener('hashchange',route);
function card(x){app.innerHTML=`<section class="card">${x}</section>`} function msg(t,bad=false){return `<div class="notice ${bad?'error':''}">${esc(t)}</div>`}
async function route(){if(!configured)return card(`<h1>Setup required</h1><p>Update <code>config.js</code> with your Supabase project values, then run <code>schema.sql</code>.</p>`); const h=id(); if(h==='manage') return manage(); if(h.startsWith('manage-')) return results(h.slice(7)); if(!h)return home(); return showPoll(h)}
async function home(){card(`<span class="eyebrow">Feedback made simple</span><h1>Share your opinion</h1><p class="muted">Open a poll using its link. Administrators can create and manage polls from the management page.</p><button class="btn" onclick="location.hash='manage'">Open management</button>`)}
async function showPoll(pollId){card('<p>Loading poll…</p>');const {data:p,error}=await db.from('polls').select('*,questions(*,options(*))').eq('public_id',pollId).eq('is_published',true).single();if(error||!p)return card(`<h1>Poll not found</h1><p class="muted">Check the link or ask the poll owner.</p>`);if(p.is_closed)return card(`<h1>${esc(p.title)}</h1>${msg('This poll is closed.')}`);p.questions.sort((a,b)=>a.position-b.position);p.questions.forEach(q=>q.options?.sort((a,b)=>a.position-b.position));let body=`<span class="eyebrow">${p.kind==='vote'?'Vote':'Feedback form'}</span><h1>${esc(p.title)}</h1><p class="muted">${esc(p.description||'')}</p><form id="responseForm">`;
p.questions.forEach(q=>{body+=`<div class="field"><label>${esc(q.label)}${q.required?' *':''}</label>`;if(q.field_type==='choice')q.options.forEach(o=>body+=`<div class="option"><label><input type="${p.kind==='vote'?'checkbox':'radio'}" name="q_${q.id}" value="${o.id}"> ${esc(o.label)}</label></div>`);else if(q.field_type==='textarea')body+=`<textarea name="q_${q.id}" ${q.required?'required':''}></textarea>`;else body+=`<input type="${q.field_type==='email'?'email':'text'}" name="q_${q.id}" ${q.required?'required':''}>`;body+=`</div>`});body+=`<button class="btn">Submit response</button></form><div id="feedback"></div>`;card(body);$('#responseForm').onsubmit=e=>submitResponse(e,p)}
async function submitResponse(e,p){e.preventDefault();const f=new FormData(e.target),answers=[];for(const q of p.questions){if(q.field_type==='choice'){const vals=f.getAll(`q_${q.id}`);if(q.required&&!vals.length)return $('#feedback').innerHTML=msg(`Please answer: ${q.label}`,true);vals.forEach(v=>answers.push({question_id:q.id,option_id:v,value:null}))}else{const v=f.get(`q_${q.id}`)?.trim();if(q.required&&!v)return $('#feedback').innerHTML=msg(`Please answer: ${q.label}`,true);if(v)answers.push({question_id:q.id,value:v,option_id:null})}}const responseId=crypto.randomUUID();const {error}=await db.from('responses').insert({id:responseId,poll_id:p.id});if(error)return $('#feedback').innerHTML=msg(error.message,true);answers.forEach(a=>a.response_id=responseId);const {error:ae}=await db.from('answers').insert(answers);if(ae)return $('#feedback').innerHTML=msg(ae.message,true);e.target.remove();$('#feedback').innerHTML=msg('Thank you. Your response was submitted.')}
async function manage(){const {data:{session}}=await db.auth.getSession();if(!session)return login();dashboard()}
function login(){card(`<span class="eyebrow">Administrator</span><h1>Management</h1><form id="login"><label>Email</label><input name="email" type="email" required><label>Password</label><input name="password" type="password" required><button class="btn">Sign in</button></form><div id="feedback"></div>`);$('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),{error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)$('#feedback').innerHTML=msg(error.message,true);else dashboard()}}
async function dashboard(){card('<p>Loading management…</p>');const {data:polls}=await db.from('polls').select('*').order('created_at',{ascending:false});card(`<div class="row"><div><span class="eyebrow">Administrator</span><h1>Poll management</h1></div><div><button class="btn secondary" id="logout">Sign out</button></div></div><h2>Create poll</h2><form id="create"><label>Type</label><select name="kind"><option value="vote">Simple vote</option><option value="form">Feedback form</option></select><label>Title</label><input name="title" required><label>Description</label><textarea name="description"></textarea><div id="builder"></div><button type="button" class="btn secondary" id="addQuestion">Add question</button> <button class="btn">Create poll</button></form><h2>Your polls</h2><div class="poll-list">${(polls||[]).map(p=>`<div class="poll-item"><div><strong>${esc(p.title)}</strong><div class="muted tiny">${p.kind} · ${p.is_closed?'closed':'open'}</div></div><div><a href="#${p.public_id}">Open</a> · <a href="#manage-${p.id}">Results</a></div></div>`).join('')||'<p class="muted">No polls yet.</p>'}</div>`);let n=0;const add=()=>{$('#builder').insertAdjacentHTML('beforeend',`<div class="question-builder" data-q><label>Question</label><input name="q_label_${n}" required><div class="row"><div><label>Field type</label><select name="q_type_${n}"><option value="choice">Choices</option><option value="text">Short text</option><option value="textarea">Long text</option><option value="email">Email</option></select></div><div><label>Required</label><select name="q_required_${n}"><option value="true">Yes</option><option value="false">No</option></select></div></div><label>Options (one per line, used for Choices)</label><textarea name="q_options_${n}"></textarea></div>`);n++};add();$('#addQuestion').onclick=add;$('#logout').onclick=async()=>{await db.auth.signOut();login()};$('#create').onsubmit=e=>createPoll(e,n)}
async function results(pollId){const {data:{session}}=await db.auth.getSession();if(!session)return login();const {data:p,error}=await db.from('polls').select('*,questions(*,options(*)),responses(*,answers(*))').eq('id',pollId).single();if(error)return card(`<h1>Could not load results</h1>${msg(error.message,true)}`);const counts={};p.responses.forEach(r=>r.answers.forEach(a=>{if(a.option_id)counts[a.option_id]=(counts[a.option_id]||0)+1}));let out=`<a href="#manage">← Management</a><span class="eyebrow">Results</span><h1>${esc(p.title)}</h1><p class="muted">${p.responses.length} submitted response(s)</p>`;p.questions.sort((a,b)=>a.position-b.position).forEach(q=>{out+=`<h2>${esc(q.label)}</h2>`;if(q.field_type==='choice'){const max=Math.max(1,...q.options.map(o=>counts[o.id]||0));q.options.forEach(o=>out+=`<div class="result"><strong>${esc(o.label)}</strong> · ${counts[o.id]||0}<div class="bar"><i style="width:${100*(counts[o.id]||0)/max}%"></i></div></div>`)}else{const vals=p.responses.flatMap(r=>r.answers).filter(a=>a.question_id===q.id&&a.value).map(a=>`<li>${esc(a.value)}</li>`);out+=`<ul>${vals.join('')||'<li class="muted">No answers</li>'}</ul>`}});card(out)}
async function createPoll(e,n){e.preventDefault();const f=new FormData(e.target),public_id=crypto.randomUUID().slice(0,8),{data:p,error}=await db.from('polls').insert({public_id,title:f.get('title'),description:f.get('description'),kind:f.get('kind'),is_published:true}).select().single();if(error)return alert(error.message);for(let i=0;i<n;i++){const label=f.get(`q_label_${i}`);if(!label)continue;const {data:q,error:qe}=await db.from('questions').insert({poll_id:p.id,label,field_type:f.get(`q_type_${i}`),required:f.get(`q_required_${i}`)==='true',position:i}).select().single();if(qe)return alert(qe.message);if(q.field_type==='choice'){const opts=f.get(`q_options_${i}`).split('\n').map(x=>x.trim()).filter(Boolean);if(opts.length)await db.from('options').insert(opts.map((label,position)=>({question_id:q.id,label,position})))}}location.hash=p.public_id}
route();
